/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package knusprigerschweinsbraten.gradle.java6.sample

import groovy.transform.TypeChecked

@TypeChecked
class Library {
    Optional<String> someLibraryMethod() {
        return Optional.empty()
    }
}
